### ISSUE TITLE
Není možné načíst dokument v Editoru

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/editor#1]
Výjimka:
Remote connection failed: java.lang.IllegalArgumentException: URI is not absolute

Log:
24.3.2017 9:42:15 org.apache.catalina.core.ApplicationContext log
SEVERE: EditorDispatchServlet: Exception while executing cz.incad.kramerius.editor.share.rpc.GetKrameriusObjectQuery: java.lang.IllegalArgumentException: URI is not absolute
com.sun.jersey.api.client.ClientHandlerException: java.lang.IllegalArgumentException: URI is not absolute
	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:151)
	at com.sun.jersey.api.client.Client.handle(Client.java:648)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:507)
	at cz.incad.kramerius.editor.server.utils.ApiUtilsHelp.getJSON(ApiUtilsHelp.java:134)
	at cz.incad.kramerius.editor.server.utils.ApiUtilsHelp.getJSONasObject(ApiUtilsHelp.java:121)
	at cz.incad.kramerius.editor.server.utils.ApiUtilsHelp.item(ApiUtilsHelp.java:143)
	at cz.incad.kramerius.editor.server.GetKrameriusObjectQueryHandler.fetchTitles(GetKrameriusObjectQueryHandler.java:175)
	at cz.incad.kramerius.editor.server.GetKrameriusObjectQueryHandler.execute(GetKrameriusObjectQueryHandler.java:103)
	at cz.incad.kramerius.editor.server.GetKrameriusObjectQueryHandler.execute(GetKrameriusObjectQueryHandler.java:64)
	at net.customware.gwt.dispatch.server.AbstractDispatch.doExecute(AbstractDispatch.java:67)
	at net.customware.gwt.dispatch.server.AbstractDispatch.execute(AbstractDispatch.java:57)
	at net.customware.gwt.dispatch.server.standard.AbstractStandardDispatchServlet.execute(AbstractStandardDispatchServlet.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:643)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:563)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:615)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:421)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:879)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:617)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1760)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(Unknown Source)
	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:159)
	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:149)
	... 43 more

**Comment by filak** [comment]
Projevuje se ve verzi 5.3.4    

Podle kuloarnich informaci by to melo ve vyssich verzich K5+ fungovat, takze zaviram.
